import { home } from "@/content";

/**
 * Dotted (halftone) region-cropped map used in GlobalPresence and Corridor.
 *
 * Continents are a grid of land dots in a static SVG (`/world-dots.svg`,
 * generated by scripts/gen-worldmap.mjs), cropped to the Europe→Gulf→India
 * window so the office pins are well separated. Pins use the SAME pure-linear
 * mapping the generator uses, over the same bounds, so they land exactly right:
 *   left% = (lng - WEST)  / (EAST - WEST)
 *   top%  = (NORTH - lat) / (NORTH - SOUTH)
 *
 * IMPORTANT: BOUNDS and FRAME ratio MUST match scripts/gen-worldmap.mjs.
 */

// Keep in sync with WEST/EAST/NORTH/SOUTH in gen-worldmap.mjs
const BOUNDS = { west: -5, east: 92, north: 60, south: 2 };
const FRAME_W = 1000;
const FRAME_H = 598;

const project = (lat: number, lng: number) => ({
  left: `${((lng - BOUNDS.west) / (BOUNDS.east - BOUNDS.west)) * 100}%`,
  top: `${((BOUNDS.north - lat) / (BOUNDS.north - BOUNDS.south)) * 100}%`,
});

export function WorldMap({ height }: { height?: number } = {}) {
  const pins = home.global.pins;

  return (
    <div className="map-visual map-dots" style={height ? { height } : undefined}>
      <div
        className="map-dots-frame"
        style={{ aspectRatio: `${FRAME_W} / ${FRAME_H}` }}
        aria-label="Map of Torque Group offices across India, Dubai and Germany"
        role="img"
      >
        {/* Land dots */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src="/world-dots.svg" alt="" className="map-dots-bg" />

        {/* Office pins */}
        {pins.map((p) => (
          <span key={p.id} className="map-dots-pin" style={project(p.lat, p.lng)}>
            <span className="map-dots-dot" />
            <span className="map-dots-label">{p.label}</span>
          </span>
        ))}
      </div>
    </div>
  );
}
